version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql-arkad
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes: 
      - ./infra/docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks: 
       - arkad-network

  php:
    container_name: php-apache-arkad
    build:
      context: ./infra/docker/php
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/laravel
      - ./infra/docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./infra/docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./infra/docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

    depends_on:
      - db
    networks: 
      - arkad-network

networks: 
  arkad-network:
    driver: bridge